//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JjjJjBot.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("******************************")]
        public string DiscordToken {
            get {
                return ((string)(this["DiscordToken"]));
            }
            set {
                this["DiscordToken"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("config.xml")]
        public string ConfigFile {
            get {
                return ((string)(this["ConfigFile"]));
            }
            set {
                this["ConfigFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Downloads")]
        public string DownloadsPath {
            get {
                return ((string)(this["DownloadsPath"]));
            }
            set {
                this["DownloadsPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("******************************")]
        public string TelegramToken {
            get {
                return ((string)(this["TelegramToken"]));
            }
            set {
                this["TelegramToken"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SaveContent {
            get {
                return ((bool)(this["SaveContent"]));
            }
            set {
                this["SaveContent"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("******************************")]
        public string DiscoedTokenDebug {
            get {
                return ((string)(this["DiscoedTokenDebug"]));
            }
            set {
                this["DiscoedTokenDebug"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("******************************")]
        public string DiscoedTokenRelease {
            get {
                return ((string)(this["DiscoedTokenRelease"]));
            }
            set {
                this["DiscoedTokenRelease"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("******************************")]
        public string TelegramTokenDebug {
            get {
                return ((string)(this["TelegramTokenDebug"]));
            }
            set {
                this["TelegramTokenDebug"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("******************************")]
        public string TelegramTokenRelease {
            get {
                return ((string)(this["TelegramTokenRelease"]));
            }
            set {
                this["TelegramTokenRelease"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Runner.exe")]
        public string Runner {
            get {
                return ((string)(this["Runner"]));
            }
            set {
                this["Runner"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("JjjJj")]
        public string BotName {
            get {
                return ((string)(this["BotName"]));
            }
            set {
                this["BotName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Bot started!")]
        public string StartupMessage {
            get {
                return ((string)(this["StartupMessage"]));
            }
            set {
                this["StartupMessage"] = value;
            }
        }
    }
}
